### ISSUE TITLE
Blank page when creating a new wallet

### ISSUE THREAD

**Issue by bitcoinuser** [commerceblock/mercury-wallet#114]
Blank page when creating a new wallet

Mercurywallet version: 0.1.6
OS: Ubuntu 64

![Captura de tela de 2021-03-16 19-35-13](https://user-images.githubusercontent.com/1178856/111388955-f2af8800-868e-11eb-94f2-bd1351f4cd6f.png)

**Comment by lucaszanella** [comment]
Same here, Ubuntu 20.04

Also had to click the banner to make something appear

**Comment by 86667** [comment]
Pre-release updated to v0.1.8. Should be sorted with latest.

**Comment by bitcoinuser** [comment]
Fixed.
