### ISSUE TITLE
Error: Request failed with status code 502

### ISSUE THREAD

**Issue by bitcoinuser** [commerceblock/mercury-wallet#119]
Hi,

When I try to deposit I see this message: Error: Request failed with status code 502

Version:  0.1.8
OS: Ubuntu

![Captura de tela de 2021-03-17 12-59-41](https://user-images.githubusercontent.com/1178856/111498869-20451180-8721-11eb-9236-051eb2a09dd2.png)

**Comment by 86667** [comment]
Changed over to `"state_entity_endpoint"` to `https://beta.mercurywallet.io/` so default URL in v0.1.8 no longer worked. 

We are now running the default alongside `https://beta.mercurywallet.io/` for testers who have not seen this issue.

**Comment by 86667** [comment]
Closing. Please reopen if issue persists.
