### ISSUE TITLE
Rectangle checkbox

### ISSUE THREAD

**Issue by stakauskas** [commerceblock/mercury-wallet#140]
Image attached
![image](https://user-images.githubusercontent.com/15116193/112286627-69e2ae80-8c83-11eb-8da8-c538eea9d4fc.png)

**Comment by 86667** [comment]
Also textbox should be considered clicked when the text next to it is clicked.

**Comment by 86667** [comment]
https://github.com/commerceblock/mercury-wallet/pull/165
