### ISSUE TITLE
Confirmation box on wallet creation

### ISSUE THREAD

**Issue by stakauskas** [commerceblock/mercury-wallet#141]
After this message we probably want: Cancel / Proceed buttons vs Close

![image](https://user-images.githubusercontent.com/15116193/112286836-a7473c00-8c83-11eb-99bb-afbea7fdd4ee.png)

**Comment by 86667** [comment]
@stakauskas Recent versions should not show this error. Which verison is this?

**Comment by stakauskas** [comment]
@86667 0.2.0 - Linux

**Comment by 86667** [comment]
Removed this error in https://github.com/commerceblock/mercury-wallet/pull/149. It is no longer necessary.
