### ISSUE TITLE
Add deposit liquidity status data labels

### ISSUE THREAD

**Issue by tomt1664** [commerceblock/mercury-wallet#148]
![Screenshot 2021-03-24 at 13 37 22](https://user-images.githubusercontent.com/15906918/112319639-2cdbe380-8ca6-11eb-9234-27d7ca262bde.png)

Get liquidity values on deposit amount selection pane from `/info/coins` map. 

Defined as follows:

If there are no coins of the denomination - Liquidity: None
If there are 0 < n < 20 coins of the denomination - Liquidity: Low
If n >= 20 of the denomination - Liquidity: Med
If any denomination n > 50, label the highest THREE denominations Liquidity: High

**Comment by 86667** [comment]
https://github.com/commerceblock/mercury-wallet/pull/190
