### ISSUE TITLE
Duplicate/old statecoin entries

### ISSUE THREAD

**Issue by lawlawlaw** [commerceblock/mercury-wallet#162]
Duplicate/old entries in the statecoin list.
This occured after the follow actions:
* Registered 3 statecoins for a swap
* Waited for the swap to complete
* Performed a transfer to self
![Screenshot 2021-03-26 at 15 36 17](https://user-images.githubusercontent.com/4256700/112656891-bf68b800-8e49-11eb-9c6f-809f76662af0.png)

**Comment by tomt1664** [comment]
I got a repeated coin when using the back button during a swap.
