### ISSUE TITLE
Withdrawn UTXOs (coins) list

### ISSUE THREAD

**Issue by linnutee** [commerceblock/mercury-wallet#217]
https://www.figma.com/file/nJNKoVzdXOLZESBlIAocNV/Mercury-Wallet-UI?node-id=19%3A1241

Per discussion in the call, tried out placements in both overview and settings. Overview seems somewhat more fitting as common place for viewing the coins. Settings was less optimal and did also overload the sub navigation area. 

- Withdrawn coins list can be accessed via the menu icon, top right, which contains radio buttons with the selections
- Summary big numbers can be leveraged to show the Withdrawn totals (sum amount of btc and no. of statecoins) 
- While viewing withdrawn coins, activity and statecoin utxo's tabs are hidden – only single tab is shown
- Withdrawn "status" could also include a date next to it, making it more informative 

<img width="1572" alt="Screenshot 2021-04-09 at 18 24 08" src="https://user-images.githubusercontent.com/17774057/114204209-996f0780-9961-11eb-98b4-78dc12550dea.png">

<img width="1586" alt="Screenshot 2021-04-09 at 18 32 35" src="https://user-images.githubusercontent.com/17774057/114204592-07b3ca00-9962-11eb-9b5a-7db109bf5cae.png">

**Comment by 86667** [comment]
Also add an option for Transferred coins. 

Display all coins marked IN_TRANSFER to provide user with a way to find each transferred coins transfer_msg and the option to cancel the transfer
