### ISSUE TITLE
Not displaying deposit address 

### ISSUE THREAD

**Issue by nicosey** [commerceblock/mercury-wallet#23]
On Mac OS

When viewing the deposit address it's not sized correctly, see screenshot

![image](https://user-images.githubusercontent.com/7435272/105989144-9b326a00-6098-11eb-8bc8-541353280d23.png)

**Comment by 86667** [comment]
Fixing this with patch in version 21.27.01.a by setting default Electron Window width to fit text size.

Assigned @Vardan-Alaverdyan to handle dynamic sizing for this Panel.

**Comment by 86667** [comment]
https://github.com/commerceblock/mercury-wallet/pull/90
