### ISSUE TITLE
Click on Perform Transfer Receiver Button

### ISSUE THREAD

**Issue by nicosey** [commerceblock/mercury-wallet#25]
Not sure if this is bug or not
However when I click on perform transrer receiver button nothing happens

![image](https://user-images.githubusercontent.com/7435272/105989501-21e74700-6099-11eb-979c-07e12cd29700.png)

**Comment by 86667** [comment]
[fixed here](https://github.com/commerceblock/mercury-wallet/pull/29/commits/539de56c235a337dddb26baa1062a38a5cd251aa)
