### ISSUE TITLE
Withdraw Statecoins button 

### ISSUE THREAD

**Issue by nicosey** [commerceblock/mercury-wallet#27]
Not sure if this is bug or me being stupid

but should there be UTXO's to select

![image](https://user-images.githubusercontent.com/7435272/105990151-016bbc80-609a-11eb-877f-9cbec647747b.png)

**Comment by 86667** [comment]
[fixed here](https://github.com/commerceblock/mercury-wallet/pull/29/commits/539de56c235a337dddb26baa1062a38a5cd251aa)
