### ISSUE TITLE
Transfer receiver confirmation indication/page

### ISSUE THREAD

**Issue by tomt1664** [commerceblock/mercury-wallet#37]
Visual indication that transfer receiver has completed successfully. Currently the only thing that happens is that the transfer message box goes blank. 

A message should indicate that the process completed, what the value of the coin received is and the expiration time.

**Comment by 86667** [comment]
Notifications added [here](https://github.com/commerceblock/mercury-wallet/commit/5da0b0ee8110374bab0e352cfe936d147a85f832).

Still need to add amount and locktime to transfer received message.

**Comment by 86667** [comment]
https://github.com/commerceblock/mercury-wallet/pull/104
