### ISSUE TITLE
Update deposit confirmation status in GUI

### ISSUE THREAD

**Issue by tomt1664** [commerceblock/mercury-wallet#75]
Deposit transaction status not updating in GUI. 
![Screenshot 2021-02-24 at 23 37 38](https://user-images.githubusercontent.com/15906918/109081087-98f41780-76f9-11eb-8f55-1278bb4aff21.png)

![Screenshot 2021-02-24 at 23 37 47](https://user-images.githubusercontent.com/15906918/109081099-9e516200-76f9-11eb-9810-f465d05c4578.png)

**Comment by 86667** [comment]
[Done here](https://github.com/commerceblock/mercury-wallet/pull/86)
