### ISSUE TITLE
Wallet name and passphrase page unresponsive - Add support for multiple wallets

### ISSUE THREAD

**Issue by tomt1664** [commerceblock/mercury-wallet#76]
![Screenshot 2021-02-24 at 23 45 28](https://user-images.githubusercontent.com/15906918/109081608-77dff680-76fa-11eb-8a2a-4699a8abdf53.png)

**Comment by 86667** [comment]
Multiple wallet suport not yet implemented so boxes are unresponsive for now. Updated Issue title to add multiple wallet support.

**Comment by 86667** [comment]
[Done here](https://github.com/commerceblock/mercury-wallet/pull/92)
