### ISSUE TITLE
There are 12 recover words, not 24

### ISSUE THREAD

**Issue by tomt1664** [commerceblock/mercury-wallet#77]
![Screenshot 2021-02-24 at 23 46 56](https://user-images.githubusercontent.com/15906918/109081736-a362e100-76fa-11eb-8b1d-8a2945d82498.png)

**Comment by 86667** [comment]
I think this was intentional in the designs for UX reasons. I'll simply change the description in image to 12.

**Comment by 86667** [comment]
[fixed](https://github.com/commerceblock/mercury-wallet/commit/8f53650f061df988678e632245b372f74da31dee)
