### ISSUE TITLE
Settings styling changes

### ISSUE THREAD

**Issue by 86667** [commerceblock/mercury-wallet#96]
1.   Button text CSS doesnt handle narrow screen 
2.  `notifications` and `tutorials` CSS
3.  Changing `min_anaon_set` value causing error to display in any empty fields above it. These should be completely unlinked
4.  `LOGOUT WALLET` button should be to the left of `BACK` button
5. Re-think positioning of `DELETE WALLET` button
6. Add confirmation box with warnings after pressing `DELETE WALLET`

**Comment by vmk8826** [comment]
I am a GSoc 2021 aspirant can you assign it to me

**Comment by 86667** [comment]
> I am a GSoc 2021 aspirant can you assign it to me

Hey @vmk8826, thanks for getting involved. 

If you have any questions feel free to start a conversation in this issue.

**Comment by 86667** [comment]
Any updates here? Will re-assign if no confirmation or activity by the end of the week

**Comment by vmk8826** [comment]
I am really Sorry, I am currently going through my end semester exams, I will complete it by 28th. Thanks.

**Comment by 86667** [comment]
No worries. This is largely complete now, were moving too fast to wait that long for GUI changes unfortunetly. Woudl you like to be re-assigned?
